<a href="https://colab.research.google.com/github/aeyjeyaryan/Python_ML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 # pip install numpy
import numpy as np

In [ ]:
llist = [[1,2,3,4],[1,2,4,5],[1,2,4,5]]
arr = np.array(llist)
arr

array([[1, 2, 3, 4],
       [1, 2, 4, 5],
       [1, 2, 4, 5]])

In [ ]:
#try to create a tictactoe using this ----
order = [[1,2,3],[4,5,6],[7,8,9]]
np.array(order)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,11,2) # it gives array of elements like range function

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.linspace(0,5,10)   #linspcae is used to get equally distant elements i.e 1.66666667-1.11111111 = 0.55555556

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
#for an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(2,2)

array([[0.64286517, 0.23091311],
       [0.51022679, 0.91246128]])

In [ ]:
np.random.randn(5,6)

array([[-0.07308631, -0.69437817, -1.28580093, -0.57988455,  0.74980872,
        -1.3413175 ],
       [ 0.92351056,  2.49174615, -0.34384649, -0.57994366,  0.39899898,
        -0.68722793],
       [-0.51831968, -1.2771804 , -1.58725931,  0.15683175,  0.66460564,
         1.27042805],
       [-0.75974627,  1.38564101,  1.40072209, -1.36682131,  0.09422626,
        -0.07947991],
       [-0.08938339,  0.78521764, -0.40707239,  0.37757086, -0.87875891,
         0.28001903]])

In [ ]:
np.random.randint(1,100,10)

array([52, 74, 49, 92, 67, 46, 71, 62, 81, 54])

In [ ]:
arr.max()
#same as the indexing we did earlier...for max and min elements
#argmin/max shows the index

5

In [ ]:
arr.min()


1

In [ ]:
arr.argmax()


7

In [ ]:
arr.argmin()

0

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr2 = arr.reshape(4,3)    #while reshaping the reshape product = size of array
print(arr2)

[[1 2 3]
 [4 1 2]
 [4 5 1]
 [2 4 5]]


In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
my_array = np.arange(0, 10, 2)  # start, stop, step


In [ ]:
from numpy.random import randint

In [ ]:
x = randint(1,100)
x

59

In [ ]:
#indexing in numpy
art = np.arange(0,11)
print(art)


[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
art[2:8]   #same as indexing in lists

array([2, 3, 4, 5, 6, 7])

In [ ]:
art[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
art[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
# art[:] = 10
# art

In [ ]:
art[5:9] = 10
art

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10,  9, 10])

In [ ]:
art_dupli = art.copy()
art_dupli

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10,  9, 10])

In [ ]:
art_dupli[:] = 15
art_dupli

array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15])

In [ ]:
array4 = np.array([[1,2,4,],[9,5,6],[6,7,8]])
array4

array([[1, 2, 4],
       [9, 5, 6],
       [6, 7, 8]])

In [ ]:
array4[0]   #accessing elements at index 0

array([1, 2, 4])

In [ ]:
array4[2][2]   # to access 8 at its index(here 8 is at 2 from row and column both)

8

In [ ]:
array4[:2,1:]  #here it goes to index 1 since 2 is not taken(row) then 1 shows column from index 1 to the end


array([[2, 4],
       [5, 6]])

In [ ]:
array4[:1,2:]

array([[4]])

In [ ]:
array4[1:3]

array([[9, 5, 6],
       [6, 7, 8]])

In [ ]:
#DOUBT HOW TO DO COLUMN COLUMN ONLY?
#I GUESS I FOUND IT WE NEED ROWS IF WE HAVE TO PERFORM ANY OPERATION

In [ ]:
#conditional selection
arr5 = np.arange(0,11)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
boolean_array = arr5>6  #here it checks every element one by one
boolean_array

array([False, False, False, False, False, False, False,  True,  True,
        True,  True])

In [ ]:
arr5[boolean_array]   # it shows the values that are true onlyyy

array([ 7,  8,  9, 10])

In [ ]:
arr5[arr5<6]   #this way two lines will be in one

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr6 = np.arange(50).reshape(5,10)
arr6

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr6[2:4,3:5]   # to get a part of a huge matrix we need to do indexing based on rows and columns

array([[23, 24],
       [33, 34]])

In [ ]:
# to get 15 16 25 26
arr6[1:3,5:7]

array([[15, 16],
       [25, 26]])

In [ ]:
### to get 32 33 34 35
        # 42 43 44 45
arr6[3:,2:6]

array([[32, 33, 34, 35],
       [42, 43, 44, 45]])

In [ ]:
arr6[1:2,:1][3:4,1:2]

array([], shape=(0, 0), dtype=int64)

In [ ]:
#array arithmetic operations
#it works as same as other arithmetic operators but element by element
aat = np.arange(0,10)
aat

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
aat * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
aat - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [ ]:
aat ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
aat ** 4

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

In [ ]:
aat + aat

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
aat / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
aat / 0        # inf shows infinity as it is mathematically so

<ipython-input-117-ca7045bd6fc7>:1: RuntimeWarning: divide by zero encountered in divide
  aat / 0        # inf shows infinity as it is mathematically so
<ipython-input-117-ca7045bd6fc7>:1: RuntimeWarning: invalid value encountered in divide
  aat / 0        # inf shows infinity as it is mathematically so


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [ ]:
aat / 0   # nan means null and inf means same mathematical logic

<ipython-input-118-bc3200e16aa8>:1: RuntimeWarning: divide by zero encountered in divide
  aat / 0   # nan means null and inf means same mathematical logic
<ipython-input-118-bc3200e16aa8>:1: RuntimeWarning: invalid value encountered in divide
  aat / 0   # nan means null and inf means same mathematical logic


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [ ]:
#EXERCISES
np.zeros((1,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((1,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
array7 = np.array([[1,2,3,4,5,6,7,8,9]])
array7

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
array7[:] = 5
array7

array([[5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [ ]:
your_array = np.arange(10, 51, 2)
your_array


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
order = [[0,1,2],[3,4,5],[6,7,8]]
np.array(order)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
iden = np.eye(3,3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import numpy as np

random_number = np.random.rand()
print(random_number)


0.747840750171222


In [ ]:
from numpy.random import randint

np.random.randn(25)

array([-0.88197578,  1.71719609, -1.58696155,  0.53517689, -1.22989375,
       -1.5273108 , -1.81734462, -1.71999955,  1.80534292, -1.10834321,
        0.23725894,  0.56368857,  0.83907739,  0.66819064,  0.64031758,
        0.62065491, -0.21867724, -1.28810955,  1.44907611,  0.65495266,
        1.00427694,  1.17759044, -0.62248856,  0.63893924,  1.28259255])

In [ ]:
np.arange(0.01,1.01,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# we have to get a matrix of 2d 12 13 14 15 17 18 19 20 22 23 24 25 26
12 13 14 15
17 18 18 19
21 22 23 24




zx = [12, 13, 14, 15, 17, 18, 18, 19, 21, 22, 23, 24]

matrix = np.array(zx).reshape(3, 4)

print(matrix)



SyntaxError: ignored

In [ ]:
z=np.arange(1,26).reshape(5,5)
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# to get 20 from the above matrix
z[3][4]

20

In [ ]:
#by slicing
z[3:4,4:]

array([[20]])

In [ ]:
#to get the sum of the matrix
np.sum(z)

325

In [ ]:
#to get mean
z2 = np.sum(z)
mean = z2 / 25
print(mean)

13.0


In [ ]:
# to get standard deviation
sd = np.std(z)
sd

7.211102550927978

In [ ]:
new_mat = np.arange(1,26).reshape(5,5)
new_mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
np.sum(new_mat, axis = 0)

array([55, 60, 65, 70, 75])

In [ ]:
#for single column
col_sum1 = np.sum(new_mat[:,1])
col_sum1

60

In [ ]:
# for single row
row_sum = np.sum(new_mat[0:1])
row_sum

15

In [ ]:
# for all rows
rows_sum = np.sum(new_mat,axis=1)
rows_sum

array([ 15,  40,  65,  90, 115])

In [ ]:
array4 = np.arange(50)
array4 = array4[::-1]
print(array4)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]
